# Generated by Django 3.2.8 on 2021-10-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20211030_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
