# Generated by Django 3.2.8 on 2021-11-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_event_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='charity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='family',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fashion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='festivals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='film',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='food',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lectures',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='music',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nightlife',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='performing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sports',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='visual',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
