# Generated by Django 3.2.8 on 2021-11-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20211101_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
