# Generated by Django 3.2.8 on 2021-11-02 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_alter_user_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='family',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
